version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/frontend/agrosmart-frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/src/ia-ops/tests"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
